### PR TITLE
Externalize and consolidate character alias logic

### PR DESCRIPTION
**Pull request by iVesperX**
Re-created pull request with only my commits.
Will hope to make more changes like this in the future.

### CODE REVIEW

**Comment by BKNR** [comment]
I was actually planning on doing this exact thing myself, I'll look at it when I have some time but it seems good at a glance.

**Comment by BKNR** [comment]
It needs a bit more work, it no longer responds with an error embed if it doesn't find anything with the character name. Also names with space in them still don't work, but it looks like they would since there's some in the character nickname file.

**Comment by iVesperX** [comment]
Yeah, it just occurred to me that spaces won't even work, no matter how you spin it. Everything should be good now, I tested it to make sure it works.

**Comment by BKNR** [comment]
I used your idea but I changed the implementation to one I liked better and which also works with the existing error messages.

**Pull request merged**
