### PR TITLE
More move simplifier motions

### PR DESCRIPTION
**Pull request by theneosloth**
Added a few more common inputs to the move simplifier. I rewrote the function so it's easier to add more input replacements and move nicknames in the future but I couldn't think of anything other than ewgf right now.

I think just stripping all commas from the moves could make it easier to compare the user input to the frame data, but there might be some cases where that doesn't work.

### CODE REVIEW

**Comment by BKNR** [comment]
Doesn't seem to break anything, thanks. It might conflict with TLNBS2405's Alias feature if it's eventually added to this version as well, but we'll burn that bridge when we get to it.

**Comment by theneosloth** [comment]
I'm wondering if there's any downside to just adding `move_input = move_input.replace(',', '')` to the parser. I can't think of any instances where that would break the parser and it makes querying for strings  easier (e.g b,f,2,1,2 vs bf212)

**Comment by BKNR** [comment]
Things like Kazuya 1, 2 and 1+2 would both come out of the simplifier as 12.

**Comment by theneosloth** [comment]
From the little testing I did you would usually get the command you want since the commands like 1+2 get picked up in the first case_important run, but you're right, I can see how this can create some unwanted ambiguity. Having to type in commas for long strings is pretty annoying though, there's gotta be some solution. Maybe just stripping them after directional inputs could work

**Comment by BKNR** [comment]
This feature introduced a new bug, where you can't use certain shorthand to look up things like Geese's FC+d/f+1, if you say `!geese fcdf1` the cd part in the middle is expanded as crouch dash. As you can write that together if the FC move doesn't have a d or d/f input, it confuses the use as to why this doesn't work.

**Pull request merged**
